<a href="https://colab.research.google.com/github/pdelolmo/pdelolmo-data/blob/main/regresion_lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## APRENDIZAJE SUPERVISADO. LOS DATOS YA ESTAN ETIQUETADOS:

-REGRESION LINEAL: TENGO UN CONJUNTO DE PUNTOS Y TRENGO QUE ENCONTRAR LA RECTA QUE MAS APROXIME A LOS PUNTOS. LAS BETAS SON LOS COEFICIENTES. ESTOS COEFICIENTES MIDEN: SI YO AUMENTO X1 EN UN DETERMINADO VALOR CUANTO AUMENTARIA LA Y. HAY QUE CALCULAR LOS COEFICIENTES, LAS BETAS.


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('https://raw.githubusercontent.com/ybifoundation/Dataset/main/Salary%20Data.csv')
df

Experience Years  Salary
0                1.1   39343
1                1.2   42774
2                1.3   46205
3                1.5   37731
4                2.0   43525
5                2.2   39891
6                2.5   48266
7                2.9   56642
8                3.0   60150
9                3.2   54445
10               3.2   64445
11               3.5   60000
12               3.7   57189
13               3.8   60200
14               3.9   63218
15               4.0   55794
16               4.0   56957
17               4.1   57081
18               4.3   59095
19               4.5   61111
20               4.7   64500
21               4.9   67938
22               5.1   66029
23               5.3   83088
24               5.5   82200
25               5.9   81363
26               6.0   93940
27               6.2   91000
28               6.5   90000
29               6.8   91738
30               7.1   98273
31               7.9  101302
32               8.2  113812
33               8.5  111620
34               8.7  109431
35               9.0  105582
36               9.5  116969
37               9.6  112635
38              10.3  122391
39              10.5  121872

In [ ]:
#vamos a hacer descripciones
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Experience Years  40 non-null     float64
 1   Salary            40 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 772.0 bytes


In [ ]:
df.isnull().sum()

Experience Years    0
Salary              0
dtype: int64

In [5]:
#EN REGRESION LINEAL, TENEMOS QUE DECIR CUAL ES LA VARIABLE QUE QUIERO PREDECIR Y CUALES VOY A TOMAR COMO DATO. A LAS QUE TOMO COMO DATO LLAMO X Y LA Y ES PARA ESOS DATOS
#LO QUE YO QUIERO PREDECIR, POR ESO SUPERVISADO. YO YA SE LO QUE TENGO. LAS QUE YO TOMO COMO DATO LAS LLAMAMOS X, (EN ESTE CASO SOLO UNA COLUMNA
#EXPRIENCE YEARS). X SIEMPRE SIEMRPE SIEMPRE LOS DATOS Y LA Y ES PARA ESOS DATOS, LO QUE YO QUIERO PREDECIR. AUNQUE YO TENGO YA LA SOLUCION PARA ESOS
#40 REGISTROS (YA SABEMOS SL SALARIO) POR ESO ES SUPERVISADO. DESPUES DE CALCULAR EL MODELO, PONDREMOS OTRO DATO DISTINTOS EN LOS AÑOS DE
#EXPERIENCIA Y VEREMOS CUANTO DINERO O CUAL SERI EL SALARIO, PREDECIR EE VALOR. QUEREMOS PREDECIR SALARIO (Y=SALARIO)
x=df[['Experience Years']] #2 corchetes porque solo nos interesa una lista de valores (para luego comparar)
y=df['Salary'] #aqui nos interesa continuar ocn el formato dataset


In [6]:
x.shape ##RECOMENDABLE SIEMPRE!!!. NOS DIRA CUAL ES EL NUM DE FILAS Y DE COLUMNAS

(40, 1)

##CUANTO TRATAMOS DE APRENDIZAJE NO SUPERVISADO, TODO EL CONJUNTO DE DATOS ES CON EL QUE USAMOS PARA CREAR EL MODELO. NO HACEMOS NINGUNA DIVISION. CUANDO TRATAMOS CON SUPERVISADO, SIN EMBARGO, DIVIDIMOS EL CNJUNTO DE DATOS EN 2 O 3 CONJUNTOS. HAY 2 QUE SIEMPRE VAN A ESTAR TRAIN SET Y TEST SET. TRAIN ES PARA GENERAR EL MODELO (DE ESTE CONJUNTO LE PASAREMOS LA SOLUCION Y LOS DATOS) Y EL TEST SET ES EL OTRO SUBCONJUNTO DE DATOS A LOS QUE LE PASAS LOS DATOS PERO NO LA SOLUCION. CALCULO CUANTO ES LA SOLUCION SEGUN EL MODELO Y COMPARO CON LA SOLUCION REAL QUE YO TENGO. PUEDE HABER UNA 3RA VARIANTE DE CONJUNTO DE VALIDACION (PERO HOY NO LO VEREMOS)


In [8]:
#HAY QUE DIVIDIR LA MUESTRA EN 70/30 APROX
#PARA DIVIDIR HAY QUE USAR LA LUBRERIA TRAIN_TEST_SPLIT (dividimos entre entrenamiento y test)
#SIEMPRE PRIMERO TRAIN, DESPUE TEST, PRIMERO X, DESPUES Y !!!!!!
#PONEMOS LA FUNCION TRAINTESTSPLIT
#QUEREMOS DIVIDIR EL DATASET X Y LAS Y,
#TAMAÑO DE LA MUESTRA, 70/30% SIEMPRE O 80/20, SIEMPRE EN VALORES 0-1
#RANDOMSTATE- QUE NO COJA LAS COLUMNAS Y LAS FILAS EN ORDEN, SINO QUE LAS COJA DE MANERA ALEATORIA

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=2529)

In [9]:
##IMPORTANTE COMPROBAR UQE LOS VALORES SON LOS MISMOS
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((28, 1), (12, 1), (28,), (12,))

In [10]:
##ahora vamos a aplicar la regresion lineal,. DE SKLEARN (MODELO LINEAL, COGEMOS REGRESION LINEAL, APLICAMOS)
#IGUAL QUE CON ONEHOTENCODER, IGUAL CON KMEANS,
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model

LinearRegression()

In [11]:
#AHORA QUEREMOS APLICAR LA REGRESION LINEAL A NUESTROS DATOS DE ENTRENAMIENTO (FIT PORQUE LO APLICAMOS) A LOS DATOS DE ENTRENAMIENTO
#COMO ESTAMOS EN EL ENTRENAMIENTO, TENEMOS QUE PASARLE LA SOLUCION (APRENDIZAJE SUPERVISADO) CAJITA AZUL XQ YA HEMOS APLICADO DATOS
model.fit(x_train,y_train)

LinearRegression()

In [14]:
#YA PODEMOS VER LOS COEFICIENTES Y LA BETA0 QUE NO IBA CON NINGUNA VARIABLE (EL INTERCEPT), EL
#numero que va solo, no va con inguna X
model.intercept_


np.float64(26596.961311068262)

In [13]:
#ESTA SERIA UNA LISTA DE LAS BETAS QUE MULTIPLICAN A LAS COLUMANS DE X. COMO SOLO TENEMOS UNA COLUMNA
#SOLO DA UN VALOR

model.coef_

array([9405.61663234])

In [ ]:
#estamos diciendo que la regresion son ambos coeficientes sumados * años de exp

26596+9405 * EXPERIENCE_YEARS

In [16]:
#HEMOS COGIDO EL DATASET ETRENAMIENTO, HEMOS HECHO LA REGRESION LINEAL, HEMOS APLICADO LA REGRESION A LOS DATOS DE ENTRENAMIENTO
#TNEEMOS UN MODELO, PERO DEBEMOS SABER SI EL MODELO ES BUENO O NO Y DEBEMOS PREDECIR LOS VALORES DEL X TEST
#PARA PODER COMPARAR CON LA SOLUCION DEL XTEST
y_pred=model.predict(x_test)
y_pred

array([ 90555.15441095,  59516.61952424, 106544.70268592,  64219.42784041,
        68922.23615658, 123474.81262412,  84911.78443155,  63278.86617718,
        65159.98950364,  61397.74285071,  37883.70126987,  50111.00289191])

In [17]:
#YA TENEMOS UNA SERIE DE VALORES, PERO COMO SABER SI LA REGRESION ES BUENA O NO
#SOBRE TODO 2 METRICAS: ERROR MEDIO (VALOR QUE ME DIO LA PREDICCION, VALOR QUE TENIA YO Y LO RESTAMOS, VALOR ABSOLUTO)
#ERROR CUADRATICO MEDIO: COMO HACER VARIANZA, LA REST PARA ELEVADA AL CUADRADO Y HACIENDO LA SUMA
#PARA ELLO HAY QUE IMPORTAR VARIAS LIBRERIAS DE SKLEARN

from sklearn.metrics import mean_absolute_error,mean_squared_error

In [20]:
#APLICARLO ES MUY SENCILLO, COGEMOS LA FUNCION, Y LE DECIMOS EL VALOR REAL Y LA PREDICCION
mean_absolute_error(y_test,y_pred) #ERROR BASTANTE GRANDE

4005.9263101681768

In [19]:
#PARA HACER EL SQUARE ERROR, ES MUY SIMILAR, PERO CON SQUARE, SALDRA NUM MUCHO MAYOR PORQUE ES TODO AL CUADRADO
mean_squared_error(y_test,y_pred)

24141421.671440993

In [23]:
##TODO ESTO ES TENIENDO EN CUENTA QUE TENEMOS UNA COLUMNA, PERO Y SI TENEMOS VARIAS?
#EL PROCESO ES EXATCAMENTE EL MISMO, VAMOS A USAR UN DATASET DIFERENTES

df_bikes=pd.read_csv('bike.csv')
df_bikes.head()

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  01-01-2018       1   0     1        0        6           0   
1        2  02-01-2018       1   0     1        0        0           0   
2        3  03-01-2018       1   0     1        0        1           1   
3        4  04-01-2018       1   0     1        0        2           1   
4        5  05-01-2018       1   0     1        0        3           1   

   weathersit       temp     atemp      hum  windspeed  casual  registered  \
0           2  14.110847  18.18125  80.5833  10.749882     331         654   
1           2  14.902598  17.68695  69.6087  16.652113     131         670   
2           1   8.050924   9.47025  43.7273  16.636703     120        1229   
3           1   8.200000  10.60610  59.0435  10.739832     108        1454   
4           1   9.305237  11.46350  43.6957  12.522300      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600

In [24]:
#VAMOS A QUERER PREDECIR. VAMOS A COGER Y REPRESENTAR LA INFO QUE PODEMOS TENER
df_bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     730 non-null    int64  
 1   dteday      730 non-null    object 
 2   season      730 non-null    int64  
 3   yr          730 non-null    int64  
 4   mnth        730 non-null    int64  
 5   holiday     730 non-null    int64  
 6   weekday     730 non-null    int64  
 7   workingday  730 non-null    int64  
 8   weathersit  730 non-null    int64  
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64  
 14  registered  730 non-null    int64  
 15  cnt         730 non-null    int64  
dtypes: float64(4), int64(11), object(1)
memory usage: 91.4+ KB


In [26]:
df_bikes.describe()

instant      season          yr        mnth     holiday     weekday  \
count  730.000000  730.000000  730.000000  730.000000  730.000000  730.000000   
mean   365.500000    2.498630    0.500000    6.526027    0.028767    2.997260   
std    210.877136    1.110184    0.500343    3.450215    0.167266    2.006161   
min      1.000000    1.000000    0.000000    1.000000    0.000000    0.000000   
25%    183.250000    2.000000    0.000000    4.000000    0.000000    1.000000   
50%    365.500000    3.000000    0.500000    7.000000    0.000000    3.000000   
75%    547.750000    3.000000    1.000000   10.000000    0.000000    5.000000   
max    730.000000    4.000000    1.000000   12.000000    1.000000    6.000000   

       workingday  weathersit        temp       atemp         hum   windspeed  \
count  730.000000  730.000000  730.000000  730.000000  730.000000  730.000000   
mean     0.683562    1.394521   20.319259   23.726322   62.765175   12.763620   
std      0.465405    0.544807    7.506729    8.150308   14.237589    5.195841   
min      0.000000    1.000000    2.424346    3.953480    0.000000    1.500244   
25%      0.000000    1.000000   13.811885   16.889713   52.000000    9.041650   
50%      1.000000    1.000000   20.465826   24.368225   62.625000   12.125325   
75%      1.000000    2.000000   26.880615   30.445775   72.989575   15.625589   
max      1.000000    3.000000   35.328347   42.044800   97.250000   34.000021   

            casual   registered          cnt  
count   730.000000   730.000000   730.000000  
mean    849.249315  3658.757534  4508.006849  
std     686.479875  1559.758728  1936.011647  
min       2.000000    20.000000    22.000000  
25%     316.250000  2502.250000  3169.750000  
50%     717.000000  3664.500000  4548.500000  
75%    1096.500000  4783.250000  5966.000000  
max    3410.000000  6946.000000  8714.000000

In [27]:
#VAMOS A HACER LA REGRESION LOGISTICA MAS SENCILLA, VAMOS AC ONSIDERAR QUE NO TENEMOS FECHA, VAMOS A RETIRARLA
df_bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [31]:
df_bikes.drop(['dteday'], axis=1, inplace=True)


KeyError: "['dteday'] not found in axis"

In [32]:
df_bikes.head()

instant  season  yr  mnth  holiday  weekday  workingday  weathersit  \
0        1       1   0     1        0        6           0           2   
1        2       1   0     1        0        0           0           2   
2        3       1   0     1        0        1           1           1   
3        4       1   0     1        0        2           1           1   
4        5       1   0     1        0        3           1           1   

        temp     atemp      hum  windspeed  casual  registered   cnt  
0  14.110847  18.18125  80.5833  10.749882     331         654   985  
1  14.902598  17.68695  69.6087  16.652113     131         670   801  
2   8.050924   9.47025  43.7273  16.636703     120        1229  1349  
3   8.200000  10.60610  59.0435  10.739832     108        1454  1562  
4   9.305237  11.46350  43.6957  12.522300      82        1518  1600

In [47]:
##AHORA YA TENEMOS TODOS LOS VALORES NUMERICOS. HAGAMOS LA REGRESION. PRIMERO HACEMOS EL TRAIN TEST SPLIT
#PRIMERO HAY QUE DEFINIR QUE SON LAS X Y QUE SON Y. EN ESTE CASO PREDIGAMOS CNT EN FUNCION DEL RESTO
#VAMOS A COGER TODAS LAS COLUMNAS

x=df_bikes[['instant', 'season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'hum', 'windspeed', 'casual',
       'registered', 'cnt']] ##IMPORTANTE EL DOBLE CORCHETE!!!

y=df_bikes['temp'] #VARIABLE QUE QUEREMOS PREDECIR


In [49]:
#UNA MANERA MUY FACIL DE ESCOGER VARIABLES X ES CON COLUMNS, COPIANDO Y PEGANDO
df_bikes.columns

Index(['instant', 'season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt'],
      dtype='object')

In [50]:
##SEGMENTAMOS AHORA, SIEMPRE XTRAIN, XTEST, YTRAIN, YTEST!!!

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42) #vamos a usar 80% ahora

print(x_train.shape)
print(y_train.shape) #COMO SOLO ES UN CONJUNTO DE DATOS, LA SOLUCION, NO HAY NINGUNA COLUMNA
print(x_test.shape)
print(y_test.shape)

#VEMOS QUE COINCIDEN 584 Y 584 Y 146 Y 146. 14 COLUMNAS DE 14 VARIABLES

(584, 13)
(584,)
(146, 13)
(146,)


In [51]:
## HEMOS DESCOMPUESTO TODO YA, PODRIAMOS HACER UN STANDARSCALER, PERO PRIMERO VAMOS A CONSIDERAR UQ ENO HAY
##HAY QUE CALCULA EL MODELO, LA REGRESION LINEAL EN ESTE CASO

from sklearn.linear_model import LinearRegression
model2=LinearRegression()
model2

LinearRegression()

In [52]:
#AHORA TENEMOS YA LA CAJA NARANJA, AHORA ADAPTAMOS A NUESTROS DATOS (MOMENTO DE ENTRENAMIENTO)

model2.fit(x_train,y_train)


LinearRegression()

In [53]:
##YA ESTA TODO ENTRENADO, AHORA PODEMOS CALCYULAR LOS COEFICIENTES
model2.intercept_ ##PRIMERO INTERCEPT, EL VALOR QUE SIEMPRE VA SOLO

np.float64(0.4288699188162113)

In [54]:
## POR OTRO LADO LOS COEFS, PARA CADA UNA DE LAS VARIABLES HAY QUE TENER UN COEFICIENTE
model2.coef_

##AQUI VEMOS VALORES CON NOTACION CIENTIFICA

array([ 1.49609908e-02, -1.66055737e-01, -1.12625900e+01, -4.77404080e-01,
        1.70546343e+00, -2.62165019e-01,  2.87302488e+00,  6.59948363e-01,
        8.39849460e-02,  1.17531138e-01,  3.10627773e-03, -2.20614866e-04,
        2.88566275e-03])

In [55]:
## PARA FACILITAR TODO UN POCO,VAMOS A CREAR UNA LISTA QUE SEA DE REDONEAR A DOS DECIMALES CADA UNO DE LOS COEFICIENTES

coeficientes=[round(x, 2) for x in model2.coef_] #el for es para cada uno de los coeficientes, ESTO ES UN LIST_COMPREHENSSION
coeficientes

#VEMOS QUE TODAS LAS QUE NOS DA 0 SON NO SIGNIFICATIVAS PARA EL MODELO
#PERO SI CAMBIAMOS VARIABLE Y A "TEMP" CAMBIA TODO

[np.float64(0.01),
 np.float64(-0.17),
 np.float64(-11.26),
 np.float64(-0.48),
 np.float64(1.71),
 np.float64(-0.26),
 np.float64(2.87),
 np.float64(0.66),
 np.float64(0.08),
 np.float64(0.12),
 np.float64(0.0),
 np.float64(-0.0),
 np.float64(0.0)]

In [57]:
## AHORA ESTAMOS DICIENDO QUE LA REGRESION ES 0.429 (VALOR DE INTERCEPT) + 0.01 * LA PRIMERA COLUMNA DE X (instant)

x.columns

0.4290.01*instant-0.17*season-11.26*yr (...) ##ETC HASTA QUE TENGAMOS TODOS LOS DATOS. EN ESTE CASO LAS 3 ULTIMAS COLUMNAS QUE ESTAN A 0
                                             #NO AFECTAN O NO SON SIGNIFICATIVAS PARA LA TEMPERATURA


Index(['instant', 'season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'hum', 'windspeed', 'casual', 'registered', 'cnt'],
      dtype='object')

In [58]:
##PREDECIMOS LA TEMPERATURA AHORA CON PREDICT. VARIABLE NUEVA (PREDICCION) = CON EL DATASET DE TEST

y_pred=model2.predict(x_test)
y_pred

array([27.93527517, 29.75489606, 18.63465601, 18.67004174, 25.54453778,
       27.43155499, 15.09253118, 18.52149032, 20.35770947, 18.4006678 ,
       13.06100377, 17.82787367, 16.35556219, 12.06380254, 19.37754513,
       13.5890733 , 21.00360455, 12.49901891, 25.43684972, 23.0857608 ,
       13.35385199, 18.33536113, 24.08922613, 24.89294103, 23.68446581,
       23.68919363, 18.89256233, 13.4090607 , 25.3559365 , 18.23278955,
       18.20242199, 23.59015317, 16.25313973, 16.20769641, 15.22886446,
       22.30824379, 11.8134978 , 18.02992199, 13.85374774, 30.58731204,
       16.44960206, 20.09805912, 24.99510179, 24.98763655, 29.00637889,
       20.70885726, 28.06413537, 22.28418888, 26.29186881, 25.70554833,
       19.0985307 , 22.19280082, 26.50354659, 20.4231607 , 17.0136435 ,
       26.55735564, 13.70517672, 23.4375962 , 25.25508625, 22.22025884,
        5.40190652, 23.64550732, 26.13884404, 24.24037966, 13.42263243,
       13.87346645, 15.81072238, 26.61322621, 18.21256158, 10.84

In [61]:
##VEMOS LOS ERRORES (ABSOLUTO Y CUADRATICO) DEL YTEST Y YPRED

mean_absolute_error(y_test,y_pred)


3.7473505667132536

In [60]:
mean_squared_error(y_test,y_pred)

21.420353361514497

In [71]:
##primero ordenamos

y_pred.sort()

In [73]:
##VEMOS GRAFICAMENTE CON PLOTLY

import plotly.express as px
fig=px.line(df_bikes, x=x_test['hum'], y=y_pred, title='REGRESION LINEAL')
fig.show()

In [ ]:
##PARA EXAMEN, 3 ENTREGAS CON GOOGLE COLAB
##-ANALISIS DE CALIDAD, INSPECCION DE DATOS O LIMPIEZA DEL DATASET, DATAINFO, DESCRIBE, ISNULL... AQUI SERA ALGO MUY VISUAL
##- ANALISIS NO SUPERVISADO DE CLUSTERTING, SUPERVISADO DE CLASIFICACION Y SUPERVISADO DE REGRESION. VER QUE VARIABLES SON NUESTROS
##DATOS CUALES VARIABLES QUEREMOS PREDECIR (EN CASO DE QUE SEA SUPERVISADO), EN CASO DE SUPERVISADO, ESA DESCOMPOSICIOND EL DATASET ETC
##ANALISIS AVANZADO DE DATOS CON PYTHON. AQUI SE DARA UN DATASET CON CONTRASEÑA. ABRIMOS EL DATASET, INTRODUCIMOS LA CONTRASEÑA
#Y LO GUARDAREMOS COMO UN DATASET SIN CONTRASEÑA. SI LO SUBIMOS CON CONTRASEÑA, NO TENDREMOS ACCESO AL DATASET